
server :
  port : 8880
  
spring :
  cloud :
    gateway :
      routes :
        - id : employeeModule 
          uri : http://localhost:8081/
          predicates :
            - Path=/employee/**
       
        - id : consumerModule 
          uri : http://localhost:8082/
          predicates :
            - Path=/consumer/**