spring :
  application :
    name : property-access-service
    
  config :
    import : optional:configserver:http://localhost:8888
    
  profiles :
    active : qa
    
management :
  endpoints :
    web :
      exposure :
        include : refresh
